version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: faker
    versions:
    - 5.3.0
    - 5.8.0
  - dependency-name: botocore
    versions:
    - 1.19.47
    - 1.19.63
  - dependency-name: coverage
    versions:
    - 5.3.1
    - "5.4"
  - dependency-name: pytest
    versions:
    - 6.2.1
  - dependency-name: cryptography
    versions:
    - "3.2"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python
    versions:
    - 3.9.1.pre.slim
